name: Build JSAR native deps

on:
  workflow_dispatch:

jobs:
  build-on-macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/setup-node@v4.0.0
      with:
        node-version: 18.16.0
    - name: Build ICU library
      run: |
        git clone https://github.com/unicode-org/icu
        cd icu
        git checkout release-72-1
        cd ./icu4c/source
        ./configure --help
        ./configure --prefix=`pwd`/dist --enable-release=yes --enable-shared=yes --enable-tests=no --enable-samples=no
        make install
        ls -lsh ./dist

